name: uva-thesis-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pytorch
  - pytorch-cuda=11.7
  - pip
  - pip:
    - datasets
    - ipywidgets
    - transformers
    - tqdm
    - torchvision
    - numpy
    - pandas
    - seaborn